queue_rules:
  - name: default
    allow_inplace_checks: false
    merge_conditions:
      - check-success=ci
pull_request_rules:
  - name: auto-queue
    conditions:
      - base=main
      - -draft
    actions:
      queue:
        name: default
