queue_rules:
  - name: default
    merge_conditions:
      - check-success=ci
pull_request_rules:
  - name: queue-on-label
    conditions:
      - base=main
      - label=queue-me
    actions:
      queue:
        name: default
