queue_rules:
  - name: hbot-xorg-canary-c9162f89
    merge_conditions: []
pull_request_rules:
  - name: auto-queue
    conditions:
      - base=main
      - -draft
    actions:
      queue:
        name: hbot-xorg-canary-c9162f89
